//User Login

export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN_SUCESSFUL = 'LOGIN_SUCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//FETCH EMPLOYEE DATA

export const FETCH_EMP = 'FETCH_EMP';
export const FETCH_EMP_SUCESS = 'FETCH_EMP_SUCESS';
export const FETCH_EMP_FAILED = 'FETCH_EMP_FAILED';